apiVersion: app-scanning.apps.tanzu.vmware.com/v1alpha1
kind: ImageVulnerabilityScan
metadata:
  name: prisma-image-scan
  namespace: dev2
spec:
  image: projects.registry.vmware.com/library/helloworldv2@sha256:27c13a31dd27fb0c764435b3781102270f107b231edc61462a59cfdf723e74c4
  scanResults:
    location: tapsme/scan-results
  serviceAccountNames:
    scanner: default
    publisher: default
  steps:
  - name: scan
    image: projects.registry.vmware.com/tanzu_practice/tap-scanners-package/prisma-repo-scanning-bundle@sha256:ede11812999799a15d004a88668d0bbd5ed98b222b91f33eece9919f9dca0473
    script: |
      #!/usr/bin/env /bin/bash
      cd /
      ./image/scan-image.sh /workspace /workspace/scan.xml
    env:
    - name: SSL_CERT_DIR
      value: /etc/pki/tls/certs:/ca-cert-secret
    - name: ADDRESS
      value: https://us-west1.cloud.twistlock.com/us-4-161033339
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          key: prisma_token
          name: prisma-token
          optional: true
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          key: username
          name: prisma-access-key-secret
          optional: true
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: prisma-access-key-secret
          optional: true
    - name: DEBUG_MODE_ON
      value: "true"