apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-install-gitops-ssh-external-secret-too
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: tap-install-gitops-ssh-too
    creationPolicy: Owner
    template:
      data:
        ssh-knownhosts: "{{ .githubsshknownhosts | b64dec}}"
        ssh-privatekey: "{{ .githubsshprivatekey | b64dec }}"

  data:
  - secretKey: githubsshknownhosts
    remoteRef:
      key: unicorn
      property: githubsshknownhosts
  - secretKey: githubsshprivatekey
    remoteRef:
      key: unicorn
      property: githubsshprivatekey