apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-values-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: tap-values-external-secret
    creationPolicy: Owner
    template:
      data:
        tap-values.yml: | 
          profile: full
          ceip_policy_disclosed: true

          shared:
            ingress_domain: learn.tapsme.org
            ingress_issuer: letsencrypt-production

          buildservice:
            kp_default_repository: "tapsme/build-service"
            kp_default_repository_username: "tapsme"
            kp_default_repository_password: "{{ .kpdefaultrepositorypassword  }}"

          supply_chain: "testing_scanning"

          ootb_supply_chain_testing_scanning:
            registry:
              server: index.docker.io
              repository: tapsme
            scanning:
              image:
                template: prisma-private-image-scan-template
                policy: scan-policy
              source:
                template: prisma-blob-source-scan-template
                policy: scan-policy

          learningcenter:
            ingressClass: contour

          contour:
            envoy:
              service:
                type: LoadBalancer

          tap_gui:
            tls:
              namespace: tap-install
              secretName: tap-gui-cert
            service_type: ClusterIP
            ingressEnabled: "true"
            app_config:
              auth:
                environment: development
                providers:
                  github:
                    development:
                      clientId: 27bf9d336987f38859b7
                      clientSecret: "{{ .githubauthtaplearnclientsecret  }}"

              proxy:
                /metadata-store:
                  target: https://metadata-store-app.metadata-store:8443/api/v1
                  changeOrigin: true
                  secure: false
                  headers:
                    Authorization: "{{ .metadatastoreauthheader  }}"
                    X-Custom-Source: project-star
              app:
                baseUrl: https://tap-gui.learn.tapsme.org
              integrations:
                github:
                - host: github.com
                  token: {{ .githubintegrationtoken }}
              catalog:
                locations:
                - type: url
                  target: https://github.com/Mpluya/tap-gui-catalog/blob/main/catalog-info.yaml
              backend:
                baseUrl: https://tap-gui.learn.tapsme.org
                cors:
                  origin: https://tap-gui.learn.tapsme.org
                reading:
                  allow:
                  - host: "*.learn.tapsme.org"

          accelerator:
            ingress:
              include: true
              enable_tls: true
            tls:
              secret_name: accelerator-cert
              namespace: tap-install

          appliveview:
            ingressEnabled: true
            tls:
              secretName: app-live-view-cert
              namespace: tap-install    

          metadata_store:
            app_service_type: "ClusterIP" 
            ns_for_export_app_cert: "*"

          namespace_provisioner:
            controller: true
          
          excluded_packages:
          - grype.scanning.apps.tanzu.vmware.com

  data:
  - secretKey: kpdefaultrepositorypassword
    remoteRef:
      key: unicorn
      property: kpdefaultrepositorypassword
  - secretKey: tanzunetpassword
    remoteRef:
      key: unicorn
      property: tanzunetpassword
  - secretKey: githubintegrationtoken
    remoteRef:
      key: unicorn
      property: githubintegrationtoken
  - secretKey: metadatastoreauthheader
    remoteRef:
      key: unicorn
      property: metadatastoreauthheader
  - secretKey: githubauthtaplearnclientsecret
    remoteRef:
      key: unicorn
      property: githubauthtaplearnclientsecret
  - secretKey: tapguipostgresspassword
    remoteRef:
      key: unicorn
      property: tapguipostgresspassword
  - secretKey: githubintegrationtoken
    remoteRef:
      key: unicorn
      property: githubintegrationtoken