apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-packageinstall-setup"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-packageinstall-setup"
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/gtt/tap-packages:1.4.1
      secretRef: 
        name: tap-registry
        namespace: tap-install