apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tenant-gitops-ssh-external-secret
  namespace: tap-install
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secret-store

  target:
    name: tenant-gitops-ssh
    creationPolicy: Owner
    template:
      data:
        known_hosts: "{{ .githubsshknownhosts | b64dec}}"
        identity: "{{ .githubsshprivatekey | b64dec }}"
        identity.pub: "{{ .githubsshpublickey | b64dec }}"

  data:
  - secretKey: githubsshknownhosts
    remoteRef:
      key: unicorn
      property: githubsshknownhosts
  - secretKey: githubsshprivatekey
    remoteRef:
      key: unicorn
      property: githubsshprivatekey
  - secretKey: githubsshpublickey
    remoteRef:
      key: unicorn
      property: githubsshpublickey