---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-install-gitops-ssh
  namespace: tap-install
spec:
  toNamespaces:
  - '*'
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-install-gitops-ssh-too
  namespace: tap-install
spec:
  toNamespaces:
  - '*'