---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tenant-gitops-ssh
  annotations:
    tekton.dev/git-0: github.com
spec:
  fromNamespace: tap-install
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: tenant-gitops-ssh-too
  annotations:
    tekton.dev/git-0: github.com
spec:
  fromNamespace: tap-install